float:
  any:
  - base_args: {}
    constructor: FaissGPU
    disabled: true
    docker_tag: ann-benchmarks-faiss
    module: ann_benchmarks.algorithms.faiss_gpu
    name: faiss-gpu
    run_groups:
      base:
        args: [[4096,]]
        query_args: [[1, 2, 4, 16, 64, 256, 512, 1024, 2048]]
